name: 'S3 Uploader for GitHub Actions'
description: 'Simple GitHub action to upload contents from a GitHub repository to a S3 bucket'
author: 'matdave'

branding:
  icon: 'zap'
  color: 'purple'

runs:
  using: 'node12'
  main: './build/index.js'

inputs:
  object-format:
    description: 'The format of the object name when uploading'
    required: false
    default: ''

  upload-this-branch:
    description: 'If the current branch should have its own directory when uploading'
    required: false
    default: 'false'

  directories:
    description: 'List of directories to use, glob patterns are supported, use `;` to seperate'
    required: true

  access-key:
    description: 'Your S3 access key to use to authenicate'
    required: true

  secret-key:
    description: 'Your S3 secret key to use to authenicate'
    required: true

  endpoint-override:
    description: 'Specify a custom endpoint to upload the object to.'
    required: false

  exclude:
    description: 'Excludes any directories to not be uploaded, glob patterns are supported, use `;` to seperate'
    required: false
    default: ''

  region:
    description: 'Sets the region of the S3 bucket that it is located in'
    required: false
    default: 'us-east-1'

  bucket:
    description: 'The bucket to use when uploading objects'
    required: true

  acl:
    description: 'The ACL binding to use for every file'
    required: false
    default: 'public-read'
